'use client';

import { useState } from 'react';
import Breadcrumbs from '@/components/Breadcrumbs';
import { Calculator, ArrowUpRight } from 'lucide-react';
import { estimateTakeHome, PayrollInputs, taxSources } from '@/lib/takeHome';

const initial: PayrollInputs = { annualCtc: 800000, employerCosts: 21600, annualBonus: 0, monthlyEmployeePf: 1800, annualProfessionalTax: 0, additional80C: 0, hraExemption: 0, regime: 'new' };
const inr = (n: number) => `${n < 0 ? "-" : ""}\u20b9${Math.round(Math.abs(n)).toLocaleString("en-IN")}`;
export default function SalaryCalculatorPage() {
  const [input, setInput] = useState(initial);
  const [year, setYear] = useState('FY 2026–27');
  const fields: { key: Exclude<keyof PayrollInputs, 'regime'>; label: string; hint: string; max: number }[] = [
    { key: 'annualCtc', label: 'Annual CTC (₹)', hint: 'Total employer cost, up to ₹50 lakh.', max: 5000000 },
    { key: 'employerCosts', label: 'Annual non-cash employer costs (₹)', hint: 'Employer PF, gratuity, insurance and other non-cash benefits included in CTC. Default ₹21,600 is an assumption; edit from your offer.', max: 5000000 },
    { key: 'annualBonus', label: 'Annual variable pay / bonus (₹)', hint: 'Assumed paid in full for annual tax; excluded from recurring monthly cash.', max: 5000000 },
    { key: 'monthlyEmployeePf', label: 'Monthly employee PF (₹)', hint: 'Use your payslip. ₹1,800 assumes 12% of ₹15,000 pensionable pay; your contribution can differ.', max: 100000 },
    { key: 'annualProfessionalTax', label: 'Annual professional tax (₹)', hint: 'Enter the amount applicable to your state. Default zero; not every state levies this tax.', max: 2500 },
    ...(input.regime === 'old' ? [
      { key: 'additional80C' as const, label: 'Other eligible 80C investments (₹ / year)', hint: 'Excludes employee PF entered above. Combined deduction is capped at ₹1.5 lakh.', max: 150000 },
      { key: 'hraExemption' as const, label: 'Eligible annual HRA exemption (₹)', hint: 'Enter the exemption supported by your rent and salary details, not your full HRA allowance.', max: 5000000 },
    ] : []),
  ];
  let result: ReturnType<typeof estimateTakeHome> | null = null;
  let error = '';
  try { result = estimateTakeHome(input); } catch (e) { error = e instanceof Error ? e.message : 'Check the payroll amounts.'; }
  return <div className="mx-auto max-w-6xl space-y-8 px-4 py-8 sm:px-6">
    <Breadcrumbs items={[{ name: 'Salary Explorer', url: '/#salary-explorer' }, { name: 'Estimated take-home calculator' }]} />
    <div className="max-w-3xl space-y-3"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-purple-300"><Calculator className="h-4 w-4" />Estimated take-home</p><h1 className="text-3xl font-black text-white sm:text-4xl">Understand what reaches your bank.</h1><p className="text-sm leading-6 text-slate-400">Estimate post-tax pay from your actual CTC components. Employer costs, bonus timing, PF, and state taxes all affect take-home.</p></div>
    <div className="grid gap-8 rounded-3xl border border-purple-400/20 bg-[#111320] p-5 sm:p-8 lg:grid-cols-2">
      <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="tax-year" className="mb-2 block text-sm font-semibold text-slate-200">Tax year</label><select id="tax-year" value={year} onChange={e => setYear(e.target.value)} className="w-full rounded-xl border border-slate-600 bg-slate-800 p-3 text-sm text-white"><option>FY 2026–27</option><option>FY 2025–26 (AY 2026–27)</option></select></div><div><label htmlFor="tax-regime" className="mb-2 block text-sm font-semibold text-slate-200">Tax regime</label><select id="tax-regime" value={input.regime} onChange={e => setInput({ ...input, regime: e.target.value as 'new' | 'old' })} className="w-full rounded-xl border border-slate-600 bg-slate-800 p-3 text-sm text-white"><option value="new">New regime</option><option value="old">Old regime</option></select></div></div>
        {fields.map(f => <div key={f.key}><label htmlFor={`pay-${f.key}`} className="mb-2 block text-sm font-semibold text-slate-200">{f.label}</label><input id={`pay-${f.key}`} type="number" min={0} max={f.max} step={1} value={Number.isNaN(input[f.key]) ? '' : input[f.key]} onChange={e => setInput({ ...input, [f.key]: e.target.value === '' ? NaN : Number(e.target.value) })} aria-describedby={`hint-${f.key}`} className="w-full rounded-xl border border-slate-600 bg-slate-800 p-3 text-sm text-white outline-none focus:ring-2 focus:ring-purple-400" /><p id={`hint-${f.key}`} className="mt-2 text-xs leading-5 text-slate-400">{f.hint}</p></div>)}
      </div>
      <div className="space-y-6"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/5 p-6" aria-live="polite"><p className="text-xs font-bold uppercase tracking-wider text-emerald-200">Estimated monthly take-home</p><p className="mt-3 text-4xl font-black text-white">{result ? inr(result.monthlyRecurring) : '—'}</p><p className="mt-2 text-xs leading-5 text-slate-400">Recurring cash, excluding bonus payout. Tax assumes the full entered annual bonus is paid.</p>{error && <p role="alert" className="mt-3 text-sm text-rose-300">{error}</p>}</div>
        {result && <><div className="rounded-2xl border border-white/10 p-5"><h2 className="mb-4 font-bold text-white">Annual breakdown</h2><dl className="space-y-3 text-sm">{[['CTC', input.annualCtc], ['Non-cash employer costs', -input.employerCosts], ['Gross cash salary (including bonus)', result.gross], ['Employee PF', -result.employeePf], ['Professional tax', -input.annualProfessionalTax], ['Income tax including cess', -result.annualTax], ['Estimated annual net (including bonus)', result.annualNet]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-white/5 pb-2"><dt className="text-slate-400">{label}</dt><dd className="shrink-0 font-semibold text-slate-200">{inr(value as number)}</dd></div>)}</dl></div><div className="rounded-2xl border border-white/10 p-5"><h2 className="mb-3 font-bold text-white">Tax calculation · {year}</h2><dl className="space-y-2 text-xs">{[['Standard deduction', result.standardDeduction], ['80C deduction (PF included once)', result.deduction80C], ['Taxable income', result.taxableIncome], ['Slab tax before rebate', result.beforeRebate], ['Rebate / marginal relief', result.rebateAndRelief], ['Health & education cess', result.cess]].map(([label, value]) => <div key={label} className="flex justify-between gap-3"><dt className="text-slate-400">{label}</dt><dd className="text-slate-200">{inr(value as number)}</dd></div>)}</dl></div></>}
        <p className="text-xs leading-6 text-slate-400">For resident salaried individuals under 60, ordinary salary income only, and CTC up to ₹50 lakh. Excludes capital gains, other income, surcharge, employer NPS, ESI and deductions not entered here. Estimates can differ materially from payroll.</p>
      </div>
    </div>
    <details className="rounded-2xl border border-white/10 bg-[#111320] p-6" open><summary className="cursor-pointer font-bold text-white">How we calculate this</summary><div className="mt-4 space-y-3 text-sm leading-6 text-slate-400"><p>Gross cash = CTC − non-cash employer costs. Taxable income = gross cash − standard deduction − eligible deductions for the chosen regime. Recurring monthly take-home = (gross cash − bonus − employee PF − professional tax − annual income tax including cess) ÷ 12.</p><p>New regime: ₹0–4L at 0%, ₹4–8L at 5%, ₹8–12L at 10%, ₹12–16L at 15%, ₹16–20L at 20%, ₹20–24L at 25%, above ₹24L at 30%. Standard deduction ₹75,000; rebate up to taxable income ₹12L, with marginal relief immediately above it. Old regime: 0% to ₹2.5L, then 5% to ₹5L, 20% to ₹10L, 30% above; ₹50,000 standard deduction and rebate up to taxable income ₹5L. Cess is 4% after relief.</p><p>Both listed years use these rates. The ₹1.5L old-regime 80C limit includes employee PF once. HRA and professional tax are deducted only under the old regime. Employer benefits and PF inputs are payroll assumptions, not fixed percentages of your CTC.</p><p className="text-xs">Sources checked 12 September 2026. Read the <a className="text-purple-300 underline" href={taxSources.slabs} target="_blank" rel="noreferrer">Income Tax Department rates</a>, <a className="text-purple-300 underline" href={taxSources.budget2026} target="_blank" rel="noreferrer">2026 tax memorandum</a>, <a className="text-purple-300 underline" href={taxSources.deductions} target="_blank" rel="noreferrer">salary deductions</a>, and <a className="inline-flex items-center gap-1 text-purple-300 underline" href={taxSources.epf} target="_blank" rel="noreferrer">EPFO employer booklet<ArrowUpRight className="h-3 w-3" /></a>.</p></div></details>
  </div>;
}
