'use client';

import { useId, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, Compass, Download, RotateCcw, Sparkles } from 'lucide-react';
import { Answers, CareerResult, compassSteps, isAnswered, rankCareers } from '@/lib/careerCompass';

const button = 'inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold transition-colors focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-purple-400';
const money = (n: number) => `₹${n.toFixed(1)}L`;

export default function CareerCompassAssessment({ onNavigate }: { onNavigate?: () => void }) {
  const [answers, setAnswers] = useState<Answers>({});
  const [step, setStep] = useState(0);
  const [results, setResults] = useState<CareerResult[] | null>(null);
  const [selected, setSelected] = useState(0);
  const [error, setError] = useState('');
  const heading = useRef<HTMLHeadingElement>(null);
  const uid = useId();
  const current = compassSteps[step];
  const questions = compassSteps.flatMap(s => s.questions);
  const answered = questions.filter(q => answers[q.id]?.trim() && isAnswered(q, answers)).length;
  const focusHeading = () => requestAnimationFrame(() => { heading.current?.focus(); heading.current?.scrollIntoView({ block: 'nearest' }); });
  const changeStep = (next: number) => { setStep(next); setError(''); focusHeading(); };
  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    const missing = current.questions.find(q => !isAnswered(q, answers));
    if (missing) { setError(`Please answer “${missing.label}” before continuing.`); return; }
    if (step < compassSteps.length - 1) changeStep(step + 1);
    else { setResults(rankCareers(answers)); setSelected(0); setError(''); focusHeading(); }
  };
  const download = () => {
    const blob = new Blob([JSON.stringify({ assessment: 'Career Compass', version: 1, answers, results, note: 'Heuristic fit scores and illustrative salary scenarios, not hiring probabilities or guarantees.' }, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'my-career-compass.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  const result = results?.[selected];

  return <div className="overflow-hidden rounded-3xl border border-purple-400/25 bg-[#111320] text-slate-200 shadow-2xl">
    <div className="border-b border-white/10 bg-gradient-to-br from-purple-500/15 via-transparent to-indigo-500/10 p-5 sm:p-8">
      <div className="flex items-center gap-3 pr-8"><div className="rounded-2xl border border-purple-400/30 bg-purple-500/15 p-3"><Compass className="h-6 w-6 text-purple-300" /></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-purple-300">Your next chapter</p><h2 className="mt-1 text-xl font-black text-white sm:text-2xl">Career Compass</h2></div></div>
      <p className="mt-4 max-w-xl text-sm leading-6 text-slate-400">Find a direction that fits your strengths, ambitions, and real life.</p>
      <div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-300">{['30 signals', '5 thoughtful steps', 'About 5–7 minutes'].map(label => <span key={label} className="rounded-full border border-white/10 px-3 py-1.5">{label}</span>)}</div>
    </div>
    {!results ? <>
      <nav aria-label="Assessment progress" className="grid grid-cols-5 gap-1 border-b border-white/10 px-3 py-4 sm:px-8">
        {compassSteps.map((s, i) => <button type="button" key={s.title} disabled={i > step} onClick={() => changeStep(i)} aria-current={i === step ? 'step' : undefined} className={`flex flex-col items-center gap-2 rounded-lg p-1 text-center text-[10px] sm:text-xs disabled:cursor-not-allowed ${i === step ? 'text-purple-300' : 'text-slate-400'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full ${i < step ? 'bg-emerald-400/15 text-emerald-300' : i === step ? 'bg-purple-500 text-white' : 'bg-white/5'}`}>{i < step ? <Check className="h-4 w-4" /> : `0${i + 1}`}</span><span>{['Background', 'Strengths', 'Interests', 'Goals', 'Resources'][i]}</span></button>)}
      </nav>
      <form onSubmit={submit} className="p-5 sm:p-8">
        <div className="mb-6"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>STEP {step + 1} OF 5</span><span>{answered} / 30 signals captured</span></div><h3 ref={heading} tabIndex={-1} className="text-xl font-bold text-white outline-none">{current.title}</h3><p className="mt-2 text-sm text-slate-400">{current.description}</p></div>
        <div className="grid gap-5 sm:grid-cols-2">
          {current.questions.map(q => <div key={q.id} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4">
            <label id={`${uid}-${q.id}-label`} htmlFor={`${uid}-${q.id}`} className="mb-3 block text-sm font-semibold text-slate-100">{q.label}{q.optional && <span className="ml-2 text-xs font-normal text-slate-400">Optional</span>}</label>
            {q.options?.[4] === 'Advanced' ? <fieldset aria-labelledby={`${uid}-${q.id}-label`} className="min-w-0"><div className="grid grid-cols-5 gap-1.5">{q.options.map((option, index) => <label key={option} className="cursor-pointer text-center"><input className="peer sr-only" type="radio" name={`${uid}-${q.id}`} value={option} checked={answers[q.id] === option} required onChange={() => setAnswers({ ...answers, [q.id]: option })} /><span className="flex h-11 items-center justify-center rounded-xl border border-slate-600 bg-slate-800 text-sm font-bold text-slate-300 transition-colors peer-checked:border-purple-400 peer-checked:bg-purple-500/25 peer-checked:text-purple-200 peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-purple-400">{index + 1}</span><span className="sr-only">{option}</span></label>)}</div><div className="mt-2 flex justify-between text-[11px] text-slate-400"><span>None yet</span><span className="text-purple-300">{answers[q.id] || 'Choose a level'}</span><span>Advanced</span></div></fieldset> : q.options ? <select id={`${uid}-${q.id}`} value={answers[q.id] || ''} required onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })} className="w-full min-w-0 rounded-xl border border-slate-600 bg-slate-800 px-3 py-3 text-sm text-white outline-none focus:border-purple-400 focus:ring-2 focus:ring-purple-400/30"><option value="" disabled>Select your answer</option>{q.options.map(o => <option key={o} value={o}>{o}</option>)}</select> : <input id={`${uid}-${q.id}`} type={q.type} required={!q.optional} min={q.type === 'number' ? 0 : undefined} max={q.type === 'number' ? 1000 : undefined} step={q.type === 'number' ? '.1' : undefined} minLength={q.type === 'text' ? 2 : undefined} maxLength={100} placeholder={q.id === 'location' ? 'e.g. Jaipur, Rajasthan' : 'e.g. 4.5'} value={answers[q.id] || ''} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })} aria-describedby={q.hint ? `${uid}-${q.id}-hint` : undefined} className="w-full rounded-xl border border-slate-600 bg-slate-800 px-3 py-3 text-sm text-white outline-none focus:border-purple-400 focus:ring-2 focus:ring-purple-400/30" />}
            {q.hint && <p id={`${uid}-${q.id}-hint`} className="mt-2 text-xs leading-5 text-slate-400">{q.hint}</p>}
          </div>)}
        </div>
        {error && <p role="alert" className="mt-4 text-sm text-rose-300">{error}</p>}
        <div className="mt-7 flex items-center justify-between gap-3 border-t border-white/10 pt-5"><button type="button" disabled={step === 0} onClick={() => changeStep(step - 1)} className={`${button} bg-white/5 disabled:opacity-30`}><ArrowLeft className="h-4 w-4" />Back</button><button type="submit" className={`${button} bg-gradient-to-r from-purple-600 to-indigo-600 text-white hover:from-purple-500 hover:to-indigo-500`}>{step === 4 ? 'Find my matches' : 'Continue'}<ArrowRight className="h-4 w-4" /></button></div>
        <p className="mt-4 text-center text-xs leading-5 text-slate-500">Answers stay in this session and reset when you reload. No account required. Export your plan to keep a copy.</p>
      </form>
    </> : result && <div className="space-y-6 p-5 sm:p-8">
      <div><p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-emerald-300"><Sparkles className="h-4 w-4" />Your personal shortlist</p><h3 ref={heading} tabIndex={-1} className="text-2xl font-black text-white outline-none">One profile. Several possibilities.</h3><p className="mt-2 text-sm text-slate-400">Compared across {results.length} paths. Select a match to explore its full plan.</p></div>
      <div className="grid gap-3 sm:grid-cols-3">{results.slice(0, 3).map((r, i) => <button type="button" key={r.slug} onClick={() => setSelected(i)} aria-pressed={i === selected} className={`rounded-2xl border p-5 text-left transition-colors focus-visible:outline-2 focus-visible:outline-purple-400 ${i === selected ? 'border-purple-400 bg-purple-500/15' : 'border-white/10 bg-white/[.03] hover:bg-white/[.06]'}`}><div className="mb-4 flex items-center justify-between gap-2"><span className="text-xs font-semibold uppercase tracking-wider text-slate-400">{i === 0 ? 'Best fit' : `Alternative ${i}`}</span><span className="text-xl font-black text-purple-300">{r.score}%</span></div><h3 className="font-bold text-white">{r.title}</h3><p className="mt-2 text-xs text-slate-400">{r.weeks} weeks · {money(r.salary[0])}–{money(r.salary[1])} / year</p></button>)}</div>
      <section aria-label={`${result.title} plan`} className="space-y-6 rounded-2xl border border-purple-400/25 bg-gradient-to-br from-purple-500/10 to-transparent p-5 sm:p-6">
        <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs text-purple-300">{selected === 0 ? 'YOUR STRONGEST MATCH' : 'EXPLORE AN ALTERNATIVE'}</p><h3 className="mt-1 text-2xl font-black text-white">{result.title}</h3></div><div className="rounded-2xl border border-purple-400/30 bg-purple-400/10 px-4 py-3 text-center"><strong className="text-3xl text-purple-200">{result.score}%</strong><p className="text-xs text-slate-400">profile match</p></div></div>
        <div><h4 className="mb-3 font-bold text-white">Why it suits you</h4><ul className="grid gap-3 sm:grid-cols-2">{result.reasons.map(reason => <li key={reason} className="flex items-start gap-2 text-sm leading-6 text-slate-300"><Check className="mt-1 h-4 w-4 shrink-0 text-emerald-300" />{reason}</li>)}</ul></div>
        <div className="grid gap-3 sm:grid-cols-3">{[['Starting annual CTC', `${money(result.salary[0])}–${money(result.salary[1])}`], ['Learning timeline', `${result.weeks} weeks`], ['Difficulty for you', result.gaps.reduce((s, g) => s + g.gap, 0) > 10 ? 'Challenging' : result.gaps.length > 2 ? 'Moderate' : 'Approachable']].map(([label, value]) => <div key={label} className="rounded-xl bg-black/20 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-lg font-bold text-white">{value}</p></div>)}</div>
        <p className="text-xs leading-5 text-slate-400">Salary is an illustrative India entry-level planning range, not a measured probability interval. No validated outcome dataset is connected. Hiring time is additional to the estimated {result.learningHours} study hours; experience in another field does not automatically translate into senior pay.</p>
        <div><h4 className="mb-3 font-bold text-white">Your 12-month earning trajectory</h4><div className="grid gap-3 sm:grid-cols-3">{[3, 6, 12].map(month => { const ready = result.weeks <= month * 4.33; return <div key={month} className="border-l-2 border-purple-400/40 pl-4"><p className="text-xs text-purple-300">MONTH {month}</p><p className="mt-2 text-sm font-bold">{ready ? 'Portfolio + applications' : 'Build your foundations'}</p><p className="mt-1 text-xs leading-5 text-slate-400">{ready ? `If hired: ${money(result.salary[0])}–${money(result.salary[1])} annualised CTC. Timing and growth depend on offers.` : 'No new-role earnings assumed while learning.'}</p></div>; })}</div></div>
        {!!result.cautions.length && <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4"><h4 className="text-sm font-bold text-amber-200">Plan around these trade-offs</h4><ul className="mt-2 list-disc space-y-2 pl-4 text-sm leading-6 text-slate-300">{result.cautions.map(c => <li key={c}>{c}</li>)}</ul></div>}
        <div className="grid gap-6 sm:grid-cols-2"><div><h4 className="mb-3 font-bold text-white">Skills gap</h4><p className="mb-3 text-xs leading-5 text-slate-400">Comfort ratings suggest foundations to practise; they do not verify proficiency.</p><div className="flex flex-wrap gap-2">{result.gaps.length ? result.gaps.map(g => <span key={g.key} className="rounded-lg border border-white/10 px-3 py-2 text-xs capitalize">{g.key} · +{g.gap} levels</span>) : <p className="text-sm text-emerald-300">Strong foundations. Validate them through projects.</p>}</div><p className="mt-3 text-sm leading-6 text-slate-300">Validate or build: {result.skills.join(', ')}.</p></div><div><h4 className="mb-3 font-bold text-white">First 3 projects</h4><ol className="list-decimal space-y-3 pl-5 text-sm leading-6 text-slate-300">{result.projects.map(p => <li key={p}>{p}</li>)}</ol></div></div>
        <div className="rounded-xl bg-black/20 p-4"><h4 className="mb-2 font-bold text-white">Your learning & job-search plan</h4><p className="text-sm leading-6 text-slate-300">{result.learningPlan} {result.budgetPlan}</p><p className="mt-2 text-sm leading-6 text-slate-400">Search for {result.searchPlan}</p></div>
        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-5"><div><p className="text-xs text-purple-300">STRETCH TARGET</p><Link href={`/skills/${result.stretchSlug}`} onClick={onNavigate} className="mt-1 inline-block font-bold text-white underline decoration-purple-400/50 underline-offset-4">{result.stretch}</Link><p className="mt-1 text-xs text-slate-400">Build the core portfolio first, then explore the related guide.</p></div><Link href={`/skills/${result.slug}`} onClick={onNavigate} className={`${button} bg-purple-600 text-white hover:bg-purple-500`}>Explore skill blueprint<ArrowRight className="h-4 w-4" /></Link></div>
      </section>
      <details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer text-sm font-semibold">How your match score works</summary><p className="mt-3 text-xs leading-6 text-slate-400">A transparent heuristic: strengths 30%, interests 20%, background 10%, work preferences 15%, timeline 15%, goals 10%. This compares eight curated paths; it is not a hiring or salary probability. Education is a small affinity signal, never an eligibility gate. City personalises job search; optional current salary only flags a potential pay cut.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(result.dimensions).map(([name, score]) => <div key={name}><div className="mb-1 flex justify-between text-xs"><span>{name}</span><span>{score}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div style={{ width: `${score}%` }} className="h-full rounded-full bg-purple-400" /></div></div>)}</div></details>
      <details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer text-sm font-semibold">Review your 30 signals</summary><dl className="mt-4 grid gap-4 sm:grid-cols-2">{questions.map(q => <div key={q.id}><dt className="text-xs text-slate-400">{q.label}</dt><dd className="mt-1 break-words text-sm">{answers[q.id] || 'Not provided'}</dd></div>)}</dl></details>
      <div className="flex flex-wrap gap-3"><button className={`${button} bg-white/5 hover:bg-white/10`} onClick={() => { setResults(null); changeStep(0); }}><RotateCcw className="h-4 w-4" />Edit answers</button><button className={`${button} bg-white/5 hover:bg-white/10`} onClick={download}><Download className="h-4 w-4" />Export my plan</button><button className={`${button} text-slate-400 hover:text-white`} onClick={() => { setAnswers({}); setResults(null); changeStep(0); }}>Start fresh</button></div>
    </div>}
  </div>;
}
